dex:
  enabled: false
notifications:
  enabled: false
applicationSet:
  enabled: false

controller:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

server:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi

repoServer:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi

redis:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
