apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-microservicio
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-microservicio
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-microservicio
    spec:
      containers:
        - name: microservicio
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          env:
            - name: MENSAJE
              value: "{{ .Values.env.mensaje }}"
            - name: PORT
              value: "3000"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 40
            periodSeconds: 15
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 5
