apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-microservicio
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-microservicio
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-microservicio
    spec:
      containers:
        - name: microservicio
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: MENSAJE
              value: "{{ .Values.env.mensaje }}"
            - name: PORT
              value: "{{ .Values.service.targetPort }}"
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
